-- MySQL Script generated by MySQL Workbench
-- 2018年06月12日 星期二 23时15分50秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema offlineFriends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema offlineFriends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `offlineFriends` DEFAULT CHARACTER SET utf8 ;
USE `offlineFriends` ;

-- -----------------------------------------------------
-- Table `offlineFriends`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offlineFriends`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(100) NULL,
  `age` INT UNSIGNED NULL,
  `gender` INT UNSIGNED NULL,
  `city` VARCHAR(200) NULL,
  `location` VARCHAR(200) NULL,
  `longitude` VARCHAR(50) NULL,
  `latitude` VARCHAR(50) NULL,
  `stepFrequency` INT NULL,
  `heartBeat` INT NULL,
  `stepStartTime` DATETIME NULL,
  `hobby` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
